[env]
RUST_LOG = "off"

[config]
default_to_workspace = false
# reduce_output = true
time_summary = false

[tasks.deploy]
dependencies = ["sync"]
script = { file = "./scripts/deploy.sh" }

[tasks.nginx]
dependencies = ["sync"]
script = { file = "./scripts/nginx/reload.sh" }

[tasks.reset]
dependencies = ["sync"]
script = { file = "./scripts/reset.sh" }

[tasks.sync]
script = '''
rsync -av --exclude='target' /mnt/c/workspace/av1-cloud/ /home/sen/code/new-av1-workspace/av1-cloud/
'''

[tasks.sync.windows]
script = '''
echo win11
wsl rsync -av --exclude='target' ./ /home/sen/code/new-av1-workspace/av1-cloud/
'''

[tasks.pg-reset.windows]
script = '''
wsl /home/sen/.cargo/bin/diesel database reset
'''

[tasks.pg-reset.linux]
script = '''
/home/sen/.cargo/bin/diesel database reset
'''

[tasks.pg-add.windows]
script_runner = "@shell"
script = '''
wsl /home/sen/.cargo/bin/diesel migration generate ${@}
'''

[tasks.log]
script = { file = "./scripts/log.sh" }

##############################
[tasks.d]
alias = "deploy"

[tasks.n]
alias = "nginx"
script_runner = "@shell"
