[http_server]
bind = "127.0.0.1"
port = 5991

[http_server.session]
# wsl ip
url = "redis://127.0.0.1:16379"
secure = false
http_only = false
max_age_secs = 3600_00

[log]
level = "debug"

[keydb]
keydb_urls = ["redis://127.0.0.1:46371"]

[postgres]
url = "postgresql://postgres:postgres@127.0.0.1:54333/av1-cloud"
min_conn = 1
max_conn = 20

[file_system]
root_dir = "C:/workspace/av1-cloud/dev-keydb/dev-fs-root"

[email_code]
from_full = "test <test@orientphoenix.com>"
from_addr = "test@orientphoenix.com"
password = "OUIl6zlHPmVM03cj"
server = "smtp.feishu.cn"
port = 465
subject = "验证码"
template_file = "./configs/email_code_template.html"
